something: haha
solace-persistence:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
  datasource:
    url: 'jdbc:oracle:thin:@(DESCRIPTION= (LOAD_BALANCE=YES) (FAILOVER=YES) (ADDRESS_LIST= (ADDRESS=(PROTOCOL=tcp)(HOST= localhost)(PORT=1521)) ) (CONNECT_DATA= (SERVICE_NAME=orcl)))'
    username: CTEST
    password: CTEST
    driver-class-name: oracle.jdbc.driver.OracleDriver
  source:
    enableTrackingId: 'true'
    enableDatabaseTimestamp: 'true'
    enableConnectorTimestamp: 'true'
    skipMismatchError: 'false'
    indicatorFlag: 'true'
    sendBatchSize: 1
    queryMax: 100
    triggerInterval: 1000
    maxDbRetry: 3
    retryInterval: 10
    retryCount: 3
    enableBufferedJpaBatch: 'true'
    bufferWaitSeconds: 5
solace:
  connector:
    management:
      session:
        host: localsthost
        msgVpn: msgvpn4
        clientUsername: u4
        clientPassword: u4pwd
      leader-election:
        mode: active_standby
        fail-over:
          max-attempts: 3
          back-off-initial-interval: 1000
          back-off-max-interval: 10000
          back-off-multiplier: 2
      queue: ""
  java:
    host: localsthost
    msgVpn: msgvpn4
    clientUsername: u4
    clientPassword: u4pwd
    connect-retries: -1
    reconnect-retries: -1
    apiProperties:
      pub_ack_window_size: 50
      pub_ack_time: 200
spring:
  cloud:
    stream:
      bindings:
        input-0:
          destination: ""
  boot:
    admin:
      client:
        instance:
          prefer-ip: 'true'
          management-url: 'http://localIP:${server.port}/actuator'
          service-url: 'http://localIP:${server.port}/'
        enabled: 'true'
        url: 'http://50.17.36.43:9500/admin'
        auto-registration: 'true'
        prefer-ip: 'true'
        username: user
        password: pass
  application:
    name: DataBase(Source)
  datasource:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 2
      idle-timeout: 500000
      max-lifetime: 540000
      connection-timeout: 5000
server:
  port: 8092
management:
  endpoint:
    health:
      show-components: never
      show-details: never
    logfile:
      external-file: log/connector/runtime.log
  endpoints:
    jmx:
      exposure:
        exclude: '*'
    web:
      exposure:
        include: 'health,metrics,loggers,logfile,channels,env,workflows,leaderelection,bindings'
        exclude: 'diskSpace,mappings'
