server:
  port: 8092
spring:
  boot:
    admin:
      client:
        instance:
          prefer-ip: true
          management-url: 'http://localIP:${server.port}/actuator'
          service-url: 'http://localIP:${server.port}/'
        enabled: true
        url: 'http://50.17.36.43:9500/admin'
        auto-registration: true
        prefer-ip: true
        username: user
        password: pass
  application:
    name: SOURCE_FINANCE_Aaron_FF_NWFILE_sadf
  cloud:
    stream:
      bindings:
        input-0:
          destination: /home/banala/Music/entityFolders/updated/SOURCE_TEST_V1/file_paths.cfg
          binder: file
        output-0:
          destination: SOURCE/FINANCE/Aaron/FF/NWFILE/sadf
          binder: solace
file:
  source:
    scheduler:
      restart_time_sec: 10
    general:
      adapter_id: SOURCE_FINANCE_Aaron_FF_NWFILE_sadf
      file_type: 4
      state_backup_path: ""
      copy_file_mode_permissions: 1
      max_file_transfer_size: 999000
      max_files_allowed: 99999
      max_bandwidth_limit: 100000000
      clear_state_on_eod: 1
      eod_time_sec: -1
      multiple_files_flag: 0
      ignoreEmptyFiles: true
    file_to_event:
      enabled: 0
      fileFormat: 4
      eventDelimiter: '|'
      jsonPath: '$.Authors[*].Books[*]'
      xPath: /class/student
    gcs:
      enabled: 0
      projectId: GCS_PROJECT_ID
      credentialsFilePath: /home/centos/pubsubplus-connector-file-2.2.0/configs/gcs/creds.json
      retrySettings:
        maxAttempts: 5
        retryDelayMultiplier: 3
        maxDurationMinutes: 2
    sftp_settings:
      enabled: 0
      ip: SFTP_HOST_ADDRESS
      port: 22
      user: SFTP_USER
      password: SFTP_PASSWORD
      strictHostKeyChecking: no
    ftp_settings:
      enabled: 0
      ip: FTP_HOST_ADDRESS
      port: 21
      user: FTP_USER
      password: FTP_PASSWORD
      secured: true
    directory_wildcard:
      wildcard_type: 0
      config_path: ""
    directory_replication:
      start_time: -1
    solace_out:
      lvq: SOURCE_FINANCE_Aaron_FF_NWFILE_sadf_LVQ
      destination: SOURCE/FINANCE/Aaron/FF/NWFILE/sadf
    command_center:
      enabled: 1
      useOutputDestinationSolaceCredentials: true
      heartbeat_enabled: 1
      heartbeat_interval: 5
      solace_base_publish_topic_heartbeat: FINANCE/NONE/Aaron/SE/FF/SOURCE/NWFILE
      solace_base_publish_topic: FINANCE/NONE/Aaron/SE/FF/SOURCE/NWFILE
      solace_messaging_mode: PERSISTENT
      events:
        fileStart: true
        fileComplete: true
      useoutputdestinationsolacecredentials: true
solace:
  connector:
    security:
      enabled: false
    error:
      handle: stop_all
    workflows:
      '0':
        enabled: true
        acknowledgment:
          publish-async: true
    management:
      leader-election:
        mode: standalone
        fail-over:
          max-attempts: 3
          back-off-initial-interval: 1000
          back-off-max-interval: 10000
          back-off-multiplier: 2
      queue: SOURCE_FINANCE_Aaron_FF_NWFILE_sadf_MGT
      session:
        host: 'tcp://localhost:55555'
        msg-vpn: default
        client-username: test
        client-password: test
  java:
    host: 'tcp://localhost:55555'
    msg-vpn: default
    client-username: test
    client-password: test
    connectRetries: -1
    reconnectRetries: -1
logging:
  level:
    root: INFO
    com.solace.connector.jms: INFO
    com.solace.connector.core: INFO
    com.solace.spring.cloud.stream.binder: INFO
    com.solacecoe.spring.cloud.stream.binders.file: TRACE
    com.solace.spring: INFO
    com.solacecoe.spring.cloud.stream.binders.file.util: INFO
  file:
    name: myapp.log
  logback:
    rollingpolicy:
      file-name-pattern: '${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz'
      max-file-size: 100MB
      max-history: 7
      total-size-cap: 1GB
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: 'diskSpace,mappings'
    jmx:
      exposure:
        exclude: '*'
  endpoint:
    logfile:
      external-file: myapp.log
    prometheus:
      enabled: false
    health:
      show-details: ALWAYS
      status:
        order:
          '0': DOWN
          '1': OUT_OF_SERVICE
          '2': RECONNECTING
          '3': UP
          '4': UNKNOWN
      show-components: never
