PassAddress=com.solace.connectors.database.source.entity.PassAddress
MessageLoad=com.solace.connectors.database.source.entity.MessageLoad
Customer=com.solace.connectors.database.source.entity.Customer
SourcePassenger=com.solace.connectors.database.source.entity.SourcePassenger
MessageLoad=com.solace.connectors.database.source.entity.MessageLoad

DB_TABLE=PassAddress,Customer,SourcePassenger


#--------------------PASS_ADDRESS--------------
PassAddress.ENABLE_DB_READ_TIME=true
PassAddress.ENABLE_DB_TRACKING_ID=true
PassAddress.ENABLE_DB_READ_INDICATOR_COLUMN=true
PassAddress.ENABLE_DB_READ_INDICATOR_BRIDGE_INPROGRESS_VALUE=true
PassAddress.ENABLE_DB_READ_INDICATOR_BRIDGE_FAILED_VALUE=true
PassAddress.ENABLE_DB_READ_RECORD_SEQUENTIAL_ORDER=true
PassAddress.ENABLE_DB_READ_INDICATOR_COLUMN_UPDATE_VALUE_INPROGRESS=true
PassAddress.ENABLE_DB_READ_INDICATOR_COLUMN_UPDATE_VALUE_PROCESSED=true
PassAddress.ENABLE_DB_READ_INDICATOR_COLUMN_DEFAULT_VALUE=true
PassAddress.ENABLE_DB_READ_INDICATOR_COLUMN_FAILED_VALUE=true


PassAddress.BINDING=
PassAddress.TOPIC=
PassAddress.LVQ_TOPIC=
PassAddress.DB_CONNECTOR_TIMESTAMP_FORMAT=yyyy/dd/MM HH:mm:ss
PassAddress.DB_MSG_HEADER_TIMESTAMP_FORMAT=yyyy/dd/MM HH:mm:ss.SSS
PassAddress.DB_CHILD_TABLE=MessageLoad
PassAddress.DB_PARENT_COLLECTION=messageLoadCol
PassAddress.DB_READ_TIME=readtime
PassAddress.DB_TRACKING_ID=
PassAddress.DB_READ_INDICATOR_COLUMN=
PassAddress.PARENT_CHILD_RELATION_KEY=
PassAddress.DB_PARENT_CHILD_MODE=one2many
PassAddress.DB_READ_INDICATOR_BRIDGE_INPROGRESS_VALUE=true
PassAddress.DB_READ_INDICATOR_BRIDGE_FAILED_VALUE=true
PassAddress.DB_READ_RECORD_SEQUENTIAL_ORDER=asc
PassAddress.DB_READ_RECORD_SEQUENTIAL_INDICATOR=
PassAddress.DB_READ_INDICATOR_COLUMN_UPDATE_VALUE_INPROGRESS=p
PassAddress.DB_READ_INDICATOR_COLUMN_UPDATE_VALUE_PROCESSED=c
PassAddress.DB_READ_INDICATOR_COLUMN_DEFAULT_VALUE=n
PassAddress.DB_READ_INDICATOR_COLUMN_FAILED_VALUE=f
PassAddress.DB_TABLE=PassAddress


#--------------------END--------------


#--------------------CUSTOMER--------------
Customer.ENABLE_DB_READ_TIME=true
Customer.ENABLE_DB_TRACKING_ID=true
Customer.ENABLE_DB_READ_INDICATOR_COLUMN=true
Customer.ENABLE_DB_READ_INDICATOR_BRIDGE_INPROGRESS_VALUE=true
Customer.ENABLE_DB_READ_INDICATOR_BRIDGE_FAILED_VALUE=true
Customer.ENABLE_DB_READ_RECORD_SEQUENTIAL_ORDER=true
Customer.ENABLE_DB_READ_INDICATOR_COLUMN_UPDATE_VALUE_INPROGRESS=true
Customer.ENABLE_DB_READ_INDICATOR_COLUMN_UPDATE_VALUE_PROCESSED=true
Customer.ENABLE_DB_READ_INDICATOR_COLUMN_DEFAULT_VALUE=true
Customer.ENABLE_DB_READ_INDICATOR_COLUMN_FAILED_VALUE=true


Customer.BINDING=
Customer.TOPIC=
Customer.LVQ_TOPIC=
Customer.DB_CONNECTOR_TIMESTAMP_FORMAT=yyyy/dd/MM HH:mm:ss
Customer.DB_MSG_HEADER_TIMESTAMP_FORMAT=yyyy/dd/MM HH:mm:ss.SSS
Customer.DB_CHILD_TABLE=
Customer.DB_PARENT_COLLECTION=
Customer.DB_READ_TIME=readtime
Customer.DB_TRACKING_ID=
Customer.DB_READ_INDICATOR_COLUMN=
Customer.PARENT_CHILD_RELATION_KEY=
Customer.DB_PARENT_CHILD_MODE=one2many
Customer.DB_READ_INDICATOR_BRIDGE_INPROGRESS_VALUE=true
Customer.DB_READ_INDICATOR_BRIDGE_FAILED_VALUE=true
Customer.DB_READ_RECORD_SEQUENTIAL_ORDER=asc
Customer.DB_READ_RECORD_SEQUENTIAL_INDICATOR=
Customer.DB_READ_INDICATOR_COLUMN_UPDATE_VALUE_INPROGRESS=p
Customer.DB_READ_INDICATOR_COLUMN_UPDATE_VALUE_PROCESSED=c
Customer.DB_READ_INDICATOR_COLUMN_DEFAULT_VALUE=n
Customer.DB_READ_INDICATOR_COLUMN_FAILED_VALUE=f
Customer.DB_TABLE=Customer


#--------------------END--------------


#--------------------SOURCE_PASSENGER--------------
SourcePassenger.ENABLE_DB_READ_TIME=true
SourcePassenger.ENABLE_DB_TRACKING_ID=true
SourcePassenger.ENABLE_DB_READ_INDICATOR_COLUMN=true
SourcePassenger.ENABLE_DB_READ_INDICATOR_BRIDGE_INPROGRESS_VALUE=true
SourcePassenger.ENABLE_DB_READ_INDICATOR_BRIDGE_FAILED_VALUE=true
SourcePassenger.ENABLE_DB_READ_RECORD_SEQUENTIAL_ORDER=true
SourcePassenger.ENABLE_DB_READ_INDICATOR_COLUMN_UPDATE_VALUE_INPROGRESS=true
SourcePassenger.ENABLE_DB_READ_INDICATOR_COLUMN_UPDATE_VALUE_PROCESSED=true
SourcePassenger.ENABLE_DB_READ_INDICATOR_COLUMN_DEFAULT_VALUE=true
SourcePassenger.ENABLE_DB_READ_INDICATOR_COLUMN_FAILED_VALUE=true


SourcePassenger.BINDING=
SourcePassenger.TOPIC=
SourcePassenger.LVQ_TOPIC=
SourcePassenger.DB_CONNECTOR_TIMESTAMP_FORMAT=yyyy/dd/MM HH:mm:ss
SourcePassenger.DB_MSG_HEADER_TIMESTAMP_FORMAT=yyyy/dd/MM HH:mm:ss.SSS
SourcePassenger.DB_CHILD_TABLE=MessageLoad
SourcePassenger.DB_PARENT_COLLECTION=messageLoadCol
SourcePassenger.DB_READ_TIME=readtime
SourcePassenger.DB_TRACKING_ID=
SourcePassenger.DB_READ_INDICATOR_COLUMN=
SourcePassenger.PARENT_CHILD_RELATION_KEY=
SourcePassenger.DB_PARENT_CHILD_MODE=one2many
SourcePassenger.DB_READ_INDICATOR_BRIDGE_INPROGRESS_VALUE=true
SourcePassenger.DB_READ_INDICATOR_BRIDGE_FAILED_VALUE=true
SourcePassenger.DB_READ_RECORD_SEQUENTIAL_ORDER=asc
SourcePassenger.DB_READ_RECORD_SEQUENTIAL_INDICATOR=
SourcePassenger.DB_READ_INDICATOR_COLUMN_UPDATE_VALUE_INPROGRESS=p
SourcePassenger.DB_READ_INDICATOR_COLUMN_UPDATE_VALUE_PROCESSED=c
SourcePassenger.DB_READ_INDICATOR_COLUMN_DEFAULT_VALUE=n
SourcePassenger.DB_READ_INDICATOR_COLUMN_FAILED_VALUE=f
SourcePassenger.DB_TABLE=SourcePassenger


#--------------------END--------------


