CccConnectors=com.solace.connectors.database.source.entity.CccConnectors
Customer=com.solace.connectors.database.source.entity.Customer
CdDbEnvs=com.solace.connectors.database.source.entity.CdDbEnvs

DB_TABLE=CccConnectors,Customer,CdDbEnvs


#--------------------CCC_CONNECTORS--------------
CccConnectors.ENABLE_DB_READ_TIME=true
CccConnectors.ENABLE_DB_TRACKING_ID=true
CccConnectors.ENABLE_DB_READ_INDICATOR_COLUMN=true
CccConnectors.ENABLE_DB_READ_INDICATOR_BRIDGE_INPROGRESS_VALUE=true
CccConnectors.ENABLE_DB_READ_INDICATOR_BRIDGE_FAILED_VALUE=true
CccConnectors.ENABLE_DB_READ_RECORD_SEQUENTIAL_ORDER=true
CccConnectors.ENABLE_DB_READ_INDICATOR_COLUMN_UPDATE_VALUE_INPROGRESS=true
CccConnectors.ENABLE_DB_READ_INDICATOR_COLUMN_UPDATE_VALUE_PROCESSED=true
CccConnectors.ENABLE_DB_READ_INDICATOR_COLUMN_DEFAULT_VALUE=true
CccConnectors.ENABLE_DB_READ_INDICATOR_COLUMN_FAILED_VALUE=true


CccConnectors.BINDING=
CccConnectors.TOPIC=
CccConnectors.LVQ_TOPIC=
CccConnectors.DB_CONNECTOR_TIMESTAMP_FORMAT=yyyy/dd/MM HH:mm:ss
CccConnectors.DB_MSG_HEADER_TIMESTAMP_FORMAT=yyyy/dd/MM HH:mm:ss.SSS
CccConnectors.DB_CHILD_TABLE=
CccConnectors.DB_PARENT_COLLECTION=
CccConnectors.DB_READ_TIME=readtime
CccConnectors.DB_TRACKING_ID=
CccConnectors.DB_READ_INDICATOR_COLUMN=
CccConnectors.PARENT_CHILD_RELATION_KEY=
CccConnectors.DB_PARENT_CHILD_MODE=one2many
CccConnectors.DB_READ_INDICATOR_BRIDGE_INPROGRESS_VALUE=true
CccConnectors.DB_READ_INDICATOR_BRIDGE_FAILED_VALUE=true
CccConnectors.DB_READ_RECORD_SEQUENTIAL_ORDER=asc
CccConnectors.DB_READ_RECORD_SEQUENTIAL_INDICATOR=
CccConnectors.DB_READ_INDICATOR_COLUMN_UPDATE_VALUE_INPROGRESS=p
CccConnectors.DB_READ_INDICATOR_COLUMN_UPDATE_VALUE_PROCESSED=c
CccConnectors.DB_READ_INDICATOR_COLUMN_DEFAULT_VALUE=n
CccConnectors.DB_READ_INDICATOR_COLUMN_FAILED_VALUE=f
CccConnectors.DB_TABLE=CccConnectors


#--------------------END--------------


#--------------------CUSTOMER--------------
Customer.ENABLE_DB_READ_TIME=true
Customer.ENABLE_DB_TRACKING_ID=true
Customer.ENABLE_DB_READ_INDICATOR_COLUMN=true
Customer.ENABLE_DB_READ_INDICATOR_BRIDGE_INPROGRESS_VALUE=true
Customer.ENABLE_DB_READ_INDICATOR_BRIDGE_FAILED_VALUE=true
Customer.ENABLE_DB_READ_RECORD_SEQUENTIAL_ORDER=true
Customer.ENABLE_DB_READ_INDICATOR_COLUMN_UPDATE_VALUE_INPROGRESS=true
Customer.ENABLE_DB_READ_INDICATOR_COLUMN_UPDATE_VALUE_PROCESSED=true
Customer.ENABLE_DB_READ_INDICATOR_COLUMN_DEFAULT_VALUE=true
Customer.ENABLE_DB_READ_INDICATOR_COLUMN_FAILED_VALUE=true


Customer.BINDING=
Customer.TOPIC=
Customer.LVQ_TOPIC=
Customer.DB_CONNECTOR_TIMESTAMP_FORMAT=yyyy/dd/MM HH:mm:ss
Customer.DB_MSG_HEADER_TIMESTAMP_FORMAT=yyyy/dd/MM HH:mm:ss.SSS
Customer.DB_CHILD_TABLE=
Customer.DB_PARENT_COLLECTION=
Customer.DB_READ_TIME=readtime
Customer.DB_TRACKING_ID=
Customer.DB_READ_INDICATOR_COLUMN=
Customer.PARENT_CHILD_RELATION_KEY=
Customer.DB_PARENT_CHILD_MODE=one2many
Customer.DB_READ_INDICATOR_BRIDGE_INPROGRESS_VALUE=true
Customer.DB_READ_INDICATOR_BRIDGE_FAILED_VALUE=true
Customer.DB_READ_RECORD_SEQUENTIAL_ORDER=asc
Customer.DB_READ_RECORD_SEQUENTIAL_INDICATOR=
Customer.DB_READ_INDICATOR_COLUMN_UPDATE_VALUE_INPROGRESS=p
Customer.DB_READ_INDICATOR_COLUMN_UPDATE_VALUE_PROCESSED=c
Customer.DB_READ_INDICATOR_COLUMN_DEFAULT_VALUE=n
Customer.DB_READ_INDICATOR_COLUMN_FAILED_VALUE=f
Customer.DB_TABLE=Customer


#--------------------END--------------


#--------------------CD_DB_ENVS--------------
CdDbEnvs.ENABLE_DB_READ_TIME=true
CdDbEnvs.ENABLE_DB_TRACKING_ID=true
CdDbEnvs.ENABLE_DB_READ_INDICATOR_COLUMN=true
CdDbEnvs.ENABLE_DB_READ_INDICATOR_BRIDGE_INPROGRESS_VALUE=true
CdDbEnvs.ENABLE_DB_READ_INDICATOR_BRIDGE_FAILED_VALUE=true
CdDbEnvs.ENABLE_DB_READ_RECORD_SEQUENTIAL_ORDER=true
CdDbEnvs.ENABLE_DB_READ_INDICATOR_COLUMN_UPDATE_VALUE_INPROGRESS=true
CdDbEnvs.ENABLE_DB_READ_INDICATOR_COLUMN_UPDATE_VALUE_PROCESSED=true
CdDbEnvs.ENABLE_DB_READ_INDICATOR_COLUMN_DEFAULT_VALUE=true
CdDbEnvs.ENABLE_DB_READ_INDICATOR_COLUMN_FAILED_VALUE=true


CdDbEnvs.BINDING=
CdDbEnvs.TOPIC=
CdDbEnvs.LVQ_TOPIC=
CdDbEnvs.DB_CONNECTOR_TIMESTAMP_FORMAT=yyyy/dd/MM HH:mm:ss
CdDbEnvs.DB_MSG_HEADER_TIMESTAMP_FORMAT=yyyy/dd/MM HH:mm:ss.SSS
CdDbEnvs.DB_CHILD_TABLE=
CdDbEnvs.DB_PARENT_COLLECTION=
CdDbEnvs.DB_READ_TIME=readtime
CdDbEnvs.DB_TRACKING_ID=
CdDbEnvs.DB_READ_INDICATOR_COLUMN=
CdDbEnvs.PARENT_CHILD_RELATION_KEY=
CdDbEnvs.DB_PARENT_CHILD_MODE=one2many
CdDbEnvs.DB_READ_INDICATOR_BRIDGE_INPROGRESS_VALUE=true
CdDbEnvs.DB_READ_INDICATOR_BRIDGE_FAILED_VALUE=true
CdDbEnvs.DB_READ_RECORD_SEQUENTIAL_ORDER=asc
CdDbEnvs.DB_READ_RECORD_SEQUENTIAL_INDICATOR=
CdDbEnvs.DB_READ_INDICATOR_COLUMN_UPDATE_VALUE_INPROGRESS=p
CdDbEnvs.DB_READ_INDICATOR_COLUMN_UPDATE_VALUE_PROCESSED=c
CdDbEnvs.DB_READ_INDICATOR_COLUMN_DEFAULT_VALUE=n
CdDbEnvs.DB_READ_INDICATOR_COLUMN_FAILED_VALUE=f
CdDbEnvs.DB_TABLE=CdDbEnvs


#--------------------END--------------


