solace-connector-mapper:
    mapper-metadata:
        source-schema-type: json
        target-schema-type: sourcetable
        encrypted: null
        source-schema-name: SourcePassenger
        target-schema-name: sourcetable
    payload-mapper:
        mapper-passengerId:
            source-xpath: SourcePassenger/passengerId
            source-datatype: NUMBER
            target-xpath: SOURCE_PASSENGER/PASSENGER_ID
            target-datatype: NUMBER
        mapper-dbtrackid:
            source-xpath: SourcePassenger/dbtrackid
            source-datatype: VARCHAR2
            target-xpath: SOURCE_PASSENGER/DBTRACKID
            target-datatype: VARCHAR2
        mapper-readtime:
            source-xpath: SourcePassenger/readtime
            source-datatype: TIMESTAMP(6)
            target-xpath: SOURCE_PASSENGER/READTIME
            target-datatype: TIMESTAMP(6)
        mapper-address:
            source-xpath: SourcePassenger/address
            source-datatype: VARCHAR2
            target-xpath: SOURCE_PASSENGER/ADDRESS
            target-datatype: VARCHAR2
        mapper-birthday:
            source-xpath: SourcePassenger/birthday
            source-datatype: TIMESTAMP(6)
            target-xpath: SOURCE_PASSENGER/BIRTHDAY
            target-datatype: TIMESTAMP(6)
        mapper-blobc:
            source-xpath: SourcePassenger/blobc
            source-datatype: BLOB
            target-xpath: SOURCE_PASSENGER/BLOBC
            target-datatype: BLOB
        mapper-clobc:
            source-xpath: SourcePassenger/clobc
            source-datatype: VARCHAR2
            target-xpath: SOURCE_PASSENGER/CLOBC
            target-datatype: VARCHAR2
        mapper-contactNo:
            source-xpath: SourcePassenger/contactNo
            source-datatype: VARCHAR2
            target-xpath: SOURCE_PASSENGER/CONTACT_NO
            target-datatype: VARCHAR2
        mapper-createdAt:
            source-xpath: SourcePassenger/createdAt
            source-datatype: TIMESTAMP(6)
            target-xpath: SOURCE_PASSENGER/CREATED_AT
            target-datatype: TIMESTAMP(6)
        mapper-flag:
            source-xpath: SourcePassenger/flag
            source-datatype: VARCHAR2
            target-xpath: SOURCE_PASSENGER/FLAG
            target-datatype: VARCHAR2
        mapper-name:
            source-xpath: SourcePassenger/name
            source-datatype: VARCHAR2
            target-xpath: SOURCE_PASSENGER/NAME
            target-datatype: VARCHAR2
        mapper-nationality:
            source-xpath: SourcePassenger/nationality
            source-datatype: VARCHAR2
            target-xpath: SOURCE_PASSENGER/NATIONALITY
            target-datatype: VARCHAR2
        mapper-child-id:
            source-xpath: SourcePassenger/MessageLoad/id
            source-datatype: NUMBER
            target-xpath: SOURCE_PASSENGER/MESSAGE_LOAD/ID
            target-datatype: NUMBER
        mapper-child-load:
            source-xpath: SourcePassenger/MessageLoad/load
            source-datatype: BLOB
            target-xpath: SOURCE_PASSENGER/MESSAGE_LOAD/LOAD
            target-datatype: BLOB
        mapper-child-trackingId:
            source-xpath: SourcePassenger/MessageLoad/trackingId
            source-datatype: VARCHAR2
            target-xpath: SOURCE_PASSENGER/MESSAGE_LOAD/TRACKING_ID
            target-datatype: VARCHAR2
        mapper-child-readTime:
            source-xpath: SourcePassenger/MessageLoad/readTime
            source-datatype: DATE
            target-xpath: SOURCE_PASSENGER/MESSAGE_LOAD/READ_TIME
            target-datatype: DATE
        mapper-child-flag:
            source-xpath: SourcePassenger/MessageLoad/flag
            source-datatype: VARCHAR2
            target-xpath: SOURCE_PASSENGER/MESSAGE_LOAD/FLAG
            target-datatype: VARCHAR2
